### ISSUE TITLE
Song data file no longer available

### ISSUE THREAD

**Issue by jimmygrapes** [dlebech/lyrics-generator#11]
Kaggle seems to have removed or relocated the song data file, and I was unable to find a suitable replacement. Perhaps describing the format in order to allow custom song data would help?

**Comment by dlebech** [comment]
Hi @jimmygrapes thank you for notifying me of this, and sorry for the late reply!

The songdata dataset only needs two columns: "artist" and "text". I have updated the README to [explain this](https://github.com/dlebech/lyrics-generator#create-your-own-song-dataset) along with a few other minor improvements to the CLI in #13.

It's too bad that the dataset is not available anymore, but I hope that people will be able to create their own or find another suitable alternative :notes:
